# IPython log file

# Sat, 23 Oct 2021 18:17:13
attach('src/suciu_ribbon_knots.sage')
# Sat, 23 Oct 2021 18:17:13
sage.repl.load.load(sage.repl.load.base64.b64decode("c3JjL3N1Y2l1X3JpYmJvbl9rbm90cy5zYWdl"),globals(),True)
# Sat, 23 Oct 2021 18:17:26
k=Integer(5)
# Sat, 23 Oct 2021 18:17:41
Test=G_quotient_by_relation(Integer(5), commutator(c,d))
# Sat, 23 Oct 2021 18:17:43
Test
#[Out]# Finitely presented group < t_k, c, d | d^-1*t_k*(c*d^-1)^4*t_k*(d*c^-1)^4*t_k^-1, c^-1*t_k*c*d^-1*t_k^-1*d*t_k*d*c^-1*t_k^-1, c*d*c^-1*d^-1 >
# Sat, 23 Oct 2021 18:17:52
Test.order()
#[Out]# +Infinity
# Sat, 23 Oct 2021 18:18:05
Test.gap().StructureDescription()

GAPError: Error, reached the pre-set memory limit
(change it with the -o command line option)

Exiting Sage (CPU time 19002m59.85s, Wall time 22751m42.19s).
[MPIM metis with set_gap_memory_pool_size(50000000000)]
